### ISSUE TITLE
Allow tracing of request durations

### ISSUE THREAD

**Issue by bkircher** [gridscale/gsclient-go#186]
Something that would be nice to have in gsclient-go is a way to easily trace how long an API call needs from request → to fulfillment.

With fulfillment I mean: I'm not interested in timings for each individual API call (e.g. HTTP request → HTTP response) but rather in "create storage" → "storage created"; how long did this take?

I thought about specifying a log-level in the client configuration, e.g., `TRACE` (or whatever logrus is using). This log-level should only be used for tracing the individual requests and their timings. One line per API request, printed when the request has finished. Output format should be JSON so that it can be processed further easily.

Example: If log level is set to TRACE, you would see something like this on stderr:

```json
{
  "message": "Finished request CreateStorage",
  "requestId": "d8260ce6-7439-4543-85c4-794592a34346",
  "request": "CreateStorage",
  "success": true,
  "timeMs": 3042
}
```
timeMs is the time in milliseconds that has elapsed. success would be false when this errors, but I would still see timeMs.

What do you guys think? @fkr @nvthongswansea

**Comment by nvthongswansea** [comment]
Good idea 👍

**Comment by bkircher** [comment]
Let's put this on our plate then

**Comment by nvthongswansea** [comment]
@fkr @bkircher I've just figured out an interesting thing.
![image](https://user-images.githubusercontent.com/9968099/110640574-40208680-81b1-11eb-9dd9-39bdbb632507.png)
we can see that the `GetServer()` method takes around 1,5 second to finish, while the time it takes to get a response is 0,5 second => we spend around 1 second to do other stuff. Guess what? it because we wait before running the `targetFunc` (in this case the `targetFunc` is the function that sends the HTTP request); this affects the successful `targetFunc` badly.
![image](https://user-images.githubusercontent.com/9968099/110641640-89250a80-81b2-11eb-80dc-e2dc92b5abdc.png)
So the line 47 in the image should be moved to the post-execution of the `targetFunc`.
Result:
![image](https://user-images.githubusercontent.com/9968099/110642153-094b7000-81b3-11eb-9c13-6eaaf9024f06.png)

**Comment by bkircher** [comment]
Looks good, @nvthongswansea . Can you add a small example on how to enable tracing request timings to the README? With example output and how to interpret the value?
